
import { LanguageOption, AppLanguage } from './types';

export const BACKEND_URL = 'http://localhost:5000';

export const LANGUAGES: LanguageOption[] = [
  { value: 'en', label: 'English', flag: '🇺🇸' },
  { value: 'ta', label: 'Tamil (தமிழ்)', flag: '🇮🇳' },
  { value: 'hi', label: 'Hindi (हिन्दी)', flag: '🇮🇳' },
  { value: 'ar', label: 'Arabic (العربية)', flag: '🇸🇦' },
  { value: 'ml', label: 'Malayalam (മലയാളം)', flag: '🇮🇳' },
  { value: 'ur', label: 'Urdu (اردو)', flag: '🇵🇰' },
  { value: 'te', label: 'Telugu (తెలుగు)', flag: '🇮🇳' },
];

export const UI_TRANSLATIONS: Record<AppLanguage, any> = {
  en: {
    uploadTitle: "Upload Defect Images",
    uploadSubtitle: "3-4 clear images for better diagnosis",
    ready: "Ready",
    descriptionLabel: "Contextual Description",
    descriptionPlaceholder: "Describe the defect location, size, or age...",
    languageLabel: "Diagnosis Language",
    diagnoseBtn: "Run Analysis Module",
    running: "Processing Forensic Data...",
    summaryTitle: "Defect Analysis",
    summarySubtitle: "AI-Generated Structural Diagnostic Summary",
    primaryCause: "TECHNICAL REASONING",
    solutions: "REPAIR STEPS",
    preventive: "PREVENTIVE MEASURES",
    urgency: "URGENCY",
    newAnalysis: "Change Photos / Restart",
    confidence: "CONFIDENCE",
    evidence: "COLLECTED EVIDENCE",
    reviewNote: "HUMAN REVIEW RECOMMENDED",
    readAloud: "Read Report",
    delete: "Delete",
    change: "Change",
    add: "Add"
  },
  ta: {
    uploadTitle: "குறைபாடுள்ள படங்களை பதிவேற்றவும்",
    uploadSubtitle: "சிறந்த பரிசோதனைக்காக 3-4 தெளிவான படங்கள்",
    ready: "தயார்",
    descriptionLabel: "சூழல் விளக்கம்",
    descriptionPlaceholder: "பிரச்சினை உள்ள இடம், அளவு அல்லது வயதை விவரிக்கவும்...",
    languageLabel: "பரிசோதனை மொழி",
    diagnoseBtn: "பகுப்பாய்வைத் தொடங்கு",
    running: "தரவு செயலாக்கப்படுகிறது...",
    summaryTitle: "கண்டறியும் சுருக்கம்",
    summarySubtitle: "AI-ஆல் உருவாக்கப்பட்ட கட்டமைப்பு அறிக்கை",
    primaryCause: "தொழில்நுட்பக் காரணம்",
    solutions: "பழுதுபார்க்கும் படிகள்",
    preventive: "தடுப்பு நடவடிக்கைகள்",
    urgency: "அவசரம்",
    cost: "மதிப்பிடப்பட்ட செலவு",
    newAnalysis: "புகைப்படங்களை மாற்றவும் / மீண்டும் தொடங்கவும்",
    confidence: "நம்பிக்கை",
    evidence: "சேகரிக்கப்பட்ட சான்றுகள்",
    reviewNote: "நிபுணரின் ஆய்வு பரிந்துரைக்கப்படுகிறது",
    readAloud: "அறிக்கையை வாசிக்கவும்",
    delete: "நீக்கு",
    change: "மாற்று",
    add: "சேർ"
  },
  ar: {
    uploadTitle: "تحميل صور العيوب",
    uploadSubtitle: "3-4 صور واضحة لتشخيص أفضل",
    ready: "جاهز",
    descriptionLabel: "الوصف السياقي",
    descriptionPlaceholder: "صف موقع العيب أو حجمه أو عمره...",
    languageLabel: "لغة التشخيص",
    diagnoseBtn: "تشغيل وحدة التحليل",
    running: "جاري معالجة البيانات...",
    summaryTitle: "ملخص جنائي",
    summarySubtitle: "التشخيص الهيكلي المولد بالذكاء الاصطناعي",
    primaryCause: "التعليل الفني",
    solutions: "خطوات الإصلاح",
    preventive: "التدابير الوقائية",
    urgency: "الاستعجال",
    cost: "التكلفة التقديرية",
    newAnalysis: "تغيير الصور / البدء من جديد",
    confidence: "الثقة",
    evidence: "الأدلة التي تم جمعها",
    reviewNote: "يوصى بمراجعة بشرية",
    readAloud: "قراءة التقرير",
    delete: "حذف",
    change: "تغيير",
    add: "إضافة"
  },
  hi: {
    uploadTitle: "दोष चित्र अपलोड करें",
    uploadSubtitle: "बेहतर निदान के लिए 3-4 स्पष्ट चित्र",
    ready: "तैयार",
    descriptionLabel: "प्रासंगिक विवरण",
    descriptionPlaceholder: "दोष के स्थान, आकार या आयु का वर्णन करें...",
    languageLabel: "निदान भाषा",
    diagnoseBtn: "विश्लेषण मॉड्यूल चलाएं",
    running: "फोरेंसिक डेटा संसाधित किया जा रहा है...",
    summaryTitle: "नैदानिक सारांश",
    summarySubtitle: "AI-जनरेटेड संरचनात्मक निदान",
    primaryCause: "तकनीकी तर्क",
    solutions: "मरम्मत के कदम",
    preventive: "निवारक उपाय",
    urgency: "तात्कालिकता",
    cost: "अनुमानित लागत",
    newAnalysis: "तस्वीरें बदलें / पुनः प्रारंभ करें",
    confidence: "आत्मविश्वास",
    evidence: "एकत्रित साक्ष्य",
    reviewNote: "मानवीय समीक्षा की सिफारिश की जाती है",
    readAloud: "रिपोर्ट पढ़ें",
    delete: "हटाएं",
    change: "बदलें",
    add: "जोड़ें"
  },
  ml: {
    uploadTitle: "ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക",
    uploadSubtitle: "മികച്ച പരിശോധനയ്ക്കായി 3-4 ചിത്രങ്ങൾ",
    ready: "തയ്യാർ",
    descriptionLabel: "വിവരണം",
    descriptionPlaceholder: "പ്രശ്നം വിവരിക്കുക...",
    languageLabel: "പരിശോധന ഭാഷ",
    diagnoseBtn: "വിശകലനം നടത്തുക",
    running: "നടന്നുകൊണ്ടിരിക്കുന്നു...",
    summaryTitle: "പരിശോധന സംഗ്രഹം",
    summarySubtitle: "AI റിപ്പോർട്ട്",
    primaryCause: "സാങ്കേതിക കാരണം",
    solutions: "പരിഹാരങ്ങൾ",
    preventive: "പ്രതിരോധ മാർഗങ്ങൾ",
    urgency: "മുൻഗണന",
    cost: "ചെലവ്",
    newAnalysis: "മാറ്റുക / വീണ്ടും തുടങ്ങുക",
    confidence: "വിശ്വാസ്യത",
    evidence: "ചിത്രങ്ങൾ",
    reviewNote: "വിദഗ്ധ പരിശോധന ആവശ്യമാണ്",
    readAloud: "വായിക്കുക",
    delete: "നീക്കം ചെയ്യുക",
    change: "മാറ്റുക",
    add: "ചേർക്കുക"
  },
  ur: {
    uploadTitle: "خرابی کی تصاویر اپ لوڈ کریں",
    uploadSubtitle: "بہتر تشخیص کے لیے 3-4 واضح تصاویر",
    ready: "تیار",
    descriptionLabel: "تفصیل",
    descriptionPlaceholder: "خرابی کی جگہ، سائز یا عمر بیان کریں...",
    languageLabel: "تشخیصی زبان",
    diagnoseBtn: "تجزیاتی ماڈیول چلائیں",
    running: "ڈیٹا پروسیسنگ جاری ہے...",
    summaryTitle: "تشخیصی خلاصہ",
    summarySubtitle: "AI کی تیار کردہ رپورٹ",
    primaryCause: "تکنیکی وجہ",
    solutions: "مرمت کے مراحل",
    preventive: "احتیاطی تدابیر",
    urgency: "فوری ضرورت",
    cost: "تخمینی قیمت",
    newAnalysis: "تصاویر تبدیل کریں / دوبارہ شروع کریں",
    confidence: "اعتماد",
    evidence: "جمع شدہ ثبوت",
    reviewNote: "انسانی جائزہ کی سفارش کی جاتی ہے",
    readAloud: "رپورٹ پڑھیں",
    delete: "حذف کریں",
    change: "تبدیل کریں",
    add: "شامل کریں"
  },
  te: {
    uploadTitle: "లోపం చిత్రాలను అప్‌లోడ్ చేయండి",
    uploadSubtitle: "మెరుగైన నిర్ధారణ కోసం 3-4 స్పష్టమైన చిత్రాలు",
    ready: "సిద్ధం",
    descriptionLabel: "వివరణ",
    descriptionPlaceholder: "లోపం గురించి వివరించండి...",
    languageLabel: "నిర్ధారణ భాష",
    diagnoseBtn: "విశ్లేషణను ప్రారంభించండి",
    running: "ప్రక్రియలో ఉంది...",
    summaryTitle: "నిర్ధారణ సారాంశం",
    summarySubtitle: "AI నివేదిక",
    primaryCause: "సాంకేతిక కారణం",
    solutions: "పరిష్కార మార్గాలు",
    preventive: "నివారణ చర్యలు",
    urgency: "అవసరం",
    cost: "అంచనా వ్యయం",
    newAnalysis: "మార్చండి / మళ్ళీ ప్రారంభించండి",
    confidence: "విశ్వసనీయత",
    evidence: "సాక్ష్యాలు",
    reviewNote: "నిపుణుల సమీక్ష అవసరం",
    readAloud: "చదవండి",
    delete: "తొలగించు",
    change: "మార్చు",
    add: "జతచేయి"
  }
};

export const SEVERITY_THEMES = {
  Low: { bg: 'bg-emerald-500', text: 'text-emerald-600', border: 'border-emerald-200', light: 'bg-emerald-50' },
  Medium: { bg: 'bg-orange-500', text: 'text-orange-600', border: 'border-orange-200', light: 'bg-orange-50' },
  Immediate: { bg: 'bg-red-600', text: 'text-red-600', border: 'border-red-200', light: 'bg-red-50' },
  Severe: { bg: 'bg-red-800', text: 'text-red-800', border: 'border-red-300', light: 'bg-red-100' },
};
